name: Node.js CI Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - "node-api/**"

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: cache node modules
        uses: actions/cache@v4
        with:
          path: node-api/node_modules
          key: ${{ runner.os }}-node-${{hashFiles('node-api/package.json') }}

      - name: build docker image
        run: docker build -t my-node-app .
        working-directory: ./node-api   
